### ISSUE TITLE
如何卸载?

### ISSUE THREAD

**Issue by forliuyifei** [xmuli/lfxNet#1]
试用之后发现不如 dde-sys-monitor-plugin 好用, 等功能完善养肥了再用吧.

另外发现个bug, 不知道怎么描述, 看图↓
![截图录屏_选择区域_20210203214347](https://user-images.githubusercontent.com/53306807/106755308-f0f2ad80-6668-11eb-95b7-4d7627221c93.gif)

**Comment by XMuli** [comment]
> 试用之后发现不如 dde-sys-monitor-plugin 好用, 等功能完善养肥了再用吧.

这个能够说说具体的区别嘛？ 具体的用户体验？ 字体太大了？ 还是其它？ 可以提一些修改建议

CPU 显示不正确已经修复： [#d0a8bbd2e94](https://github.com/xmuli/lfxNet/commit/d0a8bbd2e943ca8d073a9f2bf08d064d3bd4bac5)

```bash
# 心痛我悲，安全的 卸载方式
☁  sudo rm -rf /usr/lib/dde-dock/plugins/liblfxMonitorNet.so ~/.config/lfxNet /usr/share/lfxNet
```

**Comment by forliuyifei** [comment]
> > 试用之后发现不如 dde-sys-monitor-plugin 好用, 等功能完善养肥了再用吧.
> 
> 这个能够说说具体的区别嘛？ 具体的用户体验？ 字体太大了？ 还是其它？ 可以提一些修改建议
> 
> CPU 显示不正确已经修复： [#d0a8bbd2e94](https://github.com/xmuli/lfxNet/commit/d0a8bbd2e943ca8d073a9f2bf08d064d3bd4bac5)
> 
> ```shell
> # 心痛我悲，安全的 卸载方式
> ☁  sudo rm -rf /usr/lib/dde-dock/plugins/liblfxMonitorNet.so ~/.config/lfxNet /usr/share/lfxNet
> ```

1. 这个插件, 当网速数据长度变化的时候, 会带动任务栏的其它图标, 原来那款不会.  
2. 箭头没有小三角好看.
3. 有些选项灰的.
![图片](https://user-images.githubusercontent.com/53306807/106863189-1e8c3500-6703-11eb-95f5-193ad3acc75f.png)
![图片](https://user-images.githubusercontent.com/53306807/106863240-2ba92400-6703-11eb-9261-86c0e714e163.png)

**Comment by XMuli** [comment]
@forliuyifei  可以试下新的 [v1.1.0](https://github.com/xmuli/lfxNet/releases) 版本
1. 这个我会固定下显示长度（后面就不会跳了，还提供设置）
2. 箭头还是小三角，或者其它符号，你都是可以自己自定义的，如下图
3. 设置为灰色是后面会添加新功能（可以考虑先彻底隐藏？？）


![image](https://user-images.githubusercontent.com/33887845/106865151-c1de4980-6705-11eb-8978-f923a3c54e90.png)

**Comment by forliuyifei** [comment]
> @forliuyifei 可以试下新的 [v1.1.0](https://github.com/xmuli/lfxNet/releases) 版本
> 
>     1. 这个我会固定下显示长度（后面就不会跳了，还提供设置）
> 
>     2. 箭头还是小三角，或者其它符号，你都是可以自己自定义的，如下图
> 
>     3. 设置为灰色是后面会添加新功能（可以考虑先彻底隐藏？？）
> 
> 
> ![image](https://user-images.githubusercontent.com/33887845/106865151-c1de4980-6705-11eb-8978-f923a3c54e90.png)

好的，非常感谢你的耐心回复，还有用心制作的工具 ^_^

**Comment by XMuli** [comment]
年后有空，后面还会出一个 DTK 控件写的的此网速插件。
