### ISSUE TITLE
1.1.0版本缩小行间距后，中文显示会不全。

### ISSUE THREAD

**Issue by SteveLsf** [xmuli/lfxNet#2]
![image](https://user-images.githubusercontent.com/15121676/108448520-dc372c00-729c-11eb-8ecc-3262725dd052.png)

**Comment by XMuli** [comment]
你右键点击一下刷新看看？
![image](https://user-images.githubusercontent.com/33887845/108449115-e279d800-729d-11eb-984a-12d8da0e050d.png)

**Comment by SteveLsf** [comment]
[Version] 
SystemName=deepin
SystemName[zh_CN]=深度操作系统
ProductType=Desktop
ProductType[zh_CN]=桌面
EditionName=Community
EditionName[zh_CN]=社区版
MajorVersion=20.1
MinorVersion=1030
OsBuild=11031.002

右键刷新
以及
killall dde-dock

之后显示无任何变化。

**Comment by XMuli** [comment]
**解决一：**
或者你可以修改调整字体和大小；

**解决二：**
你可以自行修改此处的间隙数值（最适合你显示器的），然后按照 README 编译和安装
https://github.com/xmuli/lfxNet/blob/58f90ca33b98fa3f181b488d99d550cf7ef6a11f/dde-dock-plugin/WinDockNet.cpp#L134

**Comment by SteveLsf** [comment]
嗯嗯，影响不大，就是说一下有这个问题。

**Comment by XMuli** [comment]
昂～， 没个显示器以及分辨都不一样，我会尽可能寻求一个最佳的数值作为平衡点
