### ISSUE TITLE
关于dock显示的占用和CPU不一样的问题

### ISSUE THREAD

**Issue by XXTX-TOP** [xmuli/lfxNet#5]
昨天在编译内核的时候 发现cpu的占用和任务管理器里显示的cpu占用和top内的cpu占用不一样 
我的cpu是4800H 编译的时候是make -j16 
请问如何解决？

**Comment by XMuli** [comment]
有截图嘛？ 你用的哪一个版本？ 我记得我修复过。最新版本是 [v2.3.0](https://github.com/xmuli/NetSpeed/releases)




![image](https://user-images.githubusercontent.com/33887845/116563481-95e0f780-a8f3-11eb-80fb-5096e6e324ba.png)

**Comment by XXTX-TOP** [comment]
感谢百忙中的回复！ 看来是我的版本太旧导致的问题 十分抱歉！

**Comment by XMuli** [comment]
早期写代码不严谨，记得泄露了一行，记得是

**Comment by XXTX-TOP** [comment]
话说能将他限制在一个框内嘛？因为现在他会随着数值的变化 一直变动长度 导致
![图片](https://user-images.githubusercontent.com/69441812/116566301-39083000-a939-11eb-9e54-06d0af4f7b09.png)
左边的这个部分一直跳动

**Comment by XMuli** [comment]
取舍问题

能够实现，不过就会有取舍。就是精度不能够设置了（过长就不能显示了）

或者将长度预设足够长（固定），但是当网速为个位的时候，前面就会显得比较空隙。

**Comment by XMuli** [comment]
这个版本的固定了（早期的简版，但是功能没有这个多），[lfxspeed](https://github.com/xmuli/lfxspeed) 可以直接在 Deepin 商店下载。
