### ISSUE TITLE
在UOS 系统下需要手动刷新才显示全

### ISSUE THREAD

**Issue by yzw20110902** [xmuli/lfxNet#7]
![77c20ff68202a2208c6edbca94dca2a](https://user-images.githubusercontent.com/16585814/118959508-f87a6000-b994-11eb-8caf-889514f780d6.png)
![6793e9ced52357b7ceaef8d72a59f31](https://user-images.githubusercontent.com/16585814/118959524-fca67d80-b994-11eb-890d-42d4afdf60b0.png)
在deepin 下不会出现
在uos下出现，uos 官方说是你这边的问题

**Comment by XMuli** [comment]
我记得是 dock 没有没有实时监测插件的添加或者减少。所以解决方案是右键点击一下刷新即可
