### ISSUE TITLE
文本宽度变化导致抖动问题任然存在

### ISSUE THREAD

**Issue by guozhiqiang123** [xmuli/lfxNet#8]
我是在之前那个仓库提issue的，发现这个问题还是没有根治。
我的建议是把这个小组件移动到最左边去，应该就没有这个问题了。
![image](https://user-images.githubusercontent.com/20378988/142797116-9d2a2e4e-f5d8-4020-9e66-bafe756e5255.png)

**Comment by XMuli** [comment]
你可以设置固定显示长度（补充空格），以及小数点的位数。

**Comment by guozhiqiang123** [comment]
好的，我试试。
